export enum AgentModel {
  ResearchAgent = "ResearchAgent",
  ResearchCollector = "ResearchCollector",
  ResearchQA = "ResearchQA",
  ScriptPlanner = "ScriptPlanner",
  ScriptWriter = "ScriptWriter",
  ScriptQA = "ScriptQA",
  VisualDirector = "VisualDirector",
  AssetStrategy = "AssetStrategy",
  ImagePromptGenerator = "ImagePromptGenerator",
  PromptEngineer = "PromptEngineer",
  ImagePromptRepair = "ImagePromptRepair",
  NarrationPlanner = "NarrationPlanner",
  PromptQA = "PromptQA",
  QAReviewer = "QAReviewer",
  MetadataWriter = "MetadataWriter",
  AssetGenerator = "AssetGenerator",
  NarrationGenerator = "NarrationGenerator",
  SubtitleGenerator = "SubtitleGenerator",
  VideoComposer = "VideoComposer",
  ReleaseValidation = "ReleaseValidation",
  ReleaseReview = "ReleaseReview",
  MetadataGenerator = "MetadataGenerator",
  ThumbnailGenerator = "ThumbnailGenerator",
  Publisher = "Publisher",
}
